baseurl = "https://defuneste.github.io/Albiziapp-blog/"
languageCode = "en-us"
publishDir = "docs"
# ici l'onglet
title = "Une présentation d'Albiziapp"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
draft = false # if set to true, changes will not be published
enableEmoji = true


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"

[params] 
    # ici c'est l'entête de la page
    description = "Une présentation d'Albiziapp"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "logo_projetReVeRIESP_small-1.png"

    [params.logo]
    url = "logo_projetReVeRIESP_small-1.png"
    width = 50
    height = 50
    alt = "unbonlogo"

