---
title: "Game of Trees à Saint-Étienne"
subtitle: Un peu de botanique, un peu d’OSM tout en testant une application web ? C’est
  possible à Saint-Etienne!
author: Olivier
date: '2019-06-11'
slug: un-peu-de-botanique-un-peu-d-osm-tout-en-testant-une-application-web-c-est-possible-à-saint-etienne
categories: []
tags:
  - carto
  - OSM
  - Saint-Etienne
---

# Un peu de botanique, un peu d’OSM tout en testant une application web ? C’est possible à Saint-Etienne!

Dans le cadre du projet [**ReVeRIES**](https://reveries-project.fr/) nous testons une application mobile (Albiziapp) de cartographie des arbres et nous avons besoin de volontaires pour l’expérimenter avec nous !

## Où ? Quand ? Et cela prend combien de temps ?

Autour de la cité du Design, le **29 juin 2019 à 14h00**, rendez vous devant le [Mixeur](https://www.openstreetmap.org/relation/3573563)[^1], environ deux heures puis le temps d’un pot pour se désaltérer !

## En quoi cela consiste ?

Localisez des arbres, identifiez les, essayez d’en prendre en photo ! Des activités vous seront proposées pour vous aider.

Puis dites nous ce que vous en avez pensé et ce qu’il faudrait améliorer.

## De quoi j’ai besoin ?

- un compte Open Street Map (OSM) deja créé (<https://www.openstreetmap.org/user/new>).  Il vous permettra de d'accéder à l'application. 


- Un smartphone avec 3G/GPS et d’une connexion internet pour vous connecter à l’application (elle est 100% en ligne et nécessite aucun téléchargement ) : [ici](https://albiziapp.reveries-project.fr/#albiziapp)

(vous pouvez tester chez vous si cela marche avant de venir)


    
Si je fais des erreurs est ce que cela va dans OSM ? 

* Tout le monde fait des erreurs ce n'est pas grave !
* Pour le moment nous n'envoyons rien dans OSM (après vérif si vous le souhaitez on le fera !)


## Vous enregistrez quoi ? 

En dehors des réponses aux questionnaires (anonymisés) qui va nous aider à en savoir plus sur votre profil l’application va enregistrer vos déplacements et bien sûr vos relevés.

## Mais je n’y connais rien en botanique !

Ce n’est pas grave l’application est conçue pour tous les niveaux (du moins dans nos têtes de chercheurs!) et les retours de débutants sont également très appréciés !

## Vous souhaitez participer ? Avoir des informations ? 

Confirmez le nous ici : [framadate](https://framadate.org/1lrFfB86J4alBlNA) ou par mail (<leroy.oli@gmail.com>) 

j’ai pas eu le temps de prévenir, je viens quand même ?
Oui bien sûr, on s’arrangera !


[^1]: 5 rue Javelin Pagnon, 42000 Saint-Étienne